apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - k8s-deployment.yaml
  - k8s-service.yaml
  - k8s-db-cluster.yaml
  - db-init-job.yaml

# Основные генераторы конфигураций и секретов (Base шаблоны)
configMapGenerator:
  - name: s5-app-config
    literals:
      - ASPNETCORE_ENVIRONMENT=Production
      - DB_HOST=s5-db-cluster-rw
      - DB_PORT=5432
      - DB_NAME=placeholder
      - DB_USER=placeholder
      - TWO_FACTOR_MODE=strict
      - TOTP__Issuer=S5

secretGenerator:
  - name: s5-app-secrets
    literals:
      - DB_PASSWORD=placeholder
      - JwtSettings__Secret=placeholder_change_me_in_overlay
      - KESTREL_CERT_PASSWORD=placeholder
      - SERVICE_USER_PASSWORD=placeholder

configurations:
  - kustomize-config.yaml
