apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: S5-postgres-cluster # Имя кластера БД
  namespace: default
spec:
  instances: 3 # Количество узлов (1 мастер, 2 реплики для надежности)
  
  # Указываем ваш собранный образ (с дампом внутри)
  imageName: my-registry.com/S5/postgres-with-dump:18.3-v1
  
  # Настройка ресурсов (CPU/RAM) для каждого узла
  resources:
    requests:
      memory: "1Gi"
      cpu: "500m"
    limits:
      memory: "2Gi"
      cpu: "1"

  # Настройка дисков (Persistent Volumes)
  storage:
    size: 20Gi
    # storageClass: "standard" # Раскомментируйте и укажите ваш StorageClass, если нужно

  # Настройки инициализации (Bootstrap)
  bootstrap:
    initdb:
      database: S5_DB     # Какую базу создать
      owner: my_app_user      # Какого пользователя создать
      # Оператор CNPG сам сгенерирует пароль и положит его в Secret

  # Порт стандартный (5432), оператор сам создаст Service для подключения