// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using S5Server.Data;

#nullable disable

namespace S5Server.Migrations
{
    [DbContext(typeof(MainDbContext))]
    [Migration("20251122224901_AddOperationalUnitToSoldier")]
    partial class AddOperationalUnitToSoldier
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("S5Server.Models.DictArea", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT(36)");

                    b.Property<string>("Comment")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT(100)");

                    b.HasKey("Id");

                    b.HasIndex("Value")
                        .IsUnique();

                    b.ToTable("dict_area", (string)null);
                });

            modelBuilder.Entity("S5Server.Models.DictForcesType", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT(36)");

                    b.Property<string>("Comment")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("ShortValue")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT(50)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT(100)");

                    b.HasKey("Id");

                    b.HasIndex("Value")
                        .IsUnique();

                    b.ToTable("dict_forces_type", (string)null);
                });

            modelBuilder.Entity("S5Server.Models.DictPosition", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT(36)");

                    b.Property<string>("Comment")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT(100)");

                    b.HasKey("Id");

                    b.HasIndex("Value")
                        .IsUnique();

                    b.ToTable("dict_position", (string)null);
                });

            modelBuilder.Entity("S5Server.Models.DictRank", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT(36)");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.Property<string>("Comment")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("NATOCode")
                        .HasColumnType("TEXT");

                    b.Property<int>("OrderVal")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ShortValue")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT(50)");

                    b.Property<string>("SubCategory")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT(100)");

                    b.HasKey("Id");

                    b.HasIndex("Value")
                        .IsUnique();

                    b.ToTable("dict_rank", null, t =>
                        {
                            t.HasComment("Військове звання");
                        });
                });

            modelBuilder.Entity("S5Server.Models.DictSoldierState", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT(36)");

                    b.Property<string>("Comment")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT(100)");

                    b.HasKey("Id");

                    b.HasIndex("Value")
                        .IsUnique();

                    b.ToTable("dict_soldier_state", (string)null);
                });

            modelBuilder.Entity("S5Server.Models.DictTemplateCategory", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT(36)");

                    b.Property<string>("Comment")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("ShortValue")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT(100)");

                    b.HasKey("Id");

                    b.HasIndex("Value")
                        .IsUnique();

                    b.ToTable("dict_template_category", (string)null);
                });

            modelBuilder.Entity("S5Server.Models.DictUnitType", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT(36)");

                    b.Property<string>("Comment")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("ShortValue")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT(50)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT(100)");

                    b.HasKey("Id");

                    b.HasIndex("Value")
                        .IsUnique();

                    b.ToTable("dict_unit_type", (string)null);
                });

            modelBuilder.Entity("S5Server.Models.DocumentTemplate", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT(36)");

                    b.Property<byte[]>("Content")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("ContentHash")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT(64)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultDataSetId")
                        .HasColumnType("TEXT(36)");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT(300)");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasColumnType("TEXT(10)");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT(150)");

                    b.Property<DateTime?>("PublishedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("TemplateCategoryId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT(36)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ContentHash");

                    b.HasIndex("DefaultDataSetId");

                    b.HasIndex("IsPublished");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("TemplateCategoryId");

                    b.ToTable("document_templates", (string)null);
                });

            modelBuilder.Entity("S5Server.Models.Soldier", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT(36)");

                    b.Property<DateTime>("ArrivedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("AssignedUnitId")
                        .HasColumnType("TEXT(36)");

                    b.Property<string>("Comment")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DepartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT(50)");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT(50)");

                    b.Property<string>("MidleName")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT(50)");

                    b.Property<string>("NickName")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT(50)");

                    b.Property<string>("OperationalUnitId")
                        .HasColumnType("TEXT(36)");

                    b.Property<string>("PositionId")
                        .IsRequired()
                        .HasColumnType("TEXT(36)");

                    b.Property<string>("RankId")
                        .IsRequired()
                        .HasColumnType("TEXT(36)");

                    b.Property<string>("StateId")
                        .IsRequired()
                        .HasColumnType("TEXT(36)");

                    b.Property<string>("UnitId")
                        .IsRequired()
                        .HasColumnType("TEXT(36)");

                    b.HasKey("Id");

                    b.HasIndex("AssignedUnitId");

                    b.HasIndex("OperationalUnitId");

                    b.HasIndex("PositionId");

                    b.HasIndex("RankId");

                    b.HasIndex("StateId");

                    b.HasIndex("UnitId");

                    b.ToTable("soldiers", (string)null);
                });

            modelBuilder.Entity("S5Server.Models.TVezhaUser<string>", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastLoginDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("RegistrationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("SoldierId")
                        .IsRequired()
                        .HasColumnType("TEXT(36)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SoldierId")
                        .IsUnique();

                    b.ToTable("TVezhaUser<string>");
                });

            modelBuilder.Entity("S5Server.Models.TemplateDataSet", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT(36)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DataJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT(150)");

                    b.Property<DateTime?>("PublishedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("TemplateId")
                        .IsRequired()
                        .HasColumnType("TEXT(36)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TemplateId", "Name")
                        .IsUnique();

                    b.ToTable("template_data_sets", (string)null);
                });

            modelBuilder.Entity("S5Server.Models.Unit", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT(36)");

                    b.Property<string>("AssignedUnitId")
                        .HasColumnType("TEXT(36)");

                    b.Property<string>("Comment")
                        .HasColumnType("TEXT");

                    b.Property<string>("ForceTypeId")
                        .HasColumnType("TEXT(36)");

                    b.Property<bool>("IsOperational")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("MilitaryNumber")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT(100)");

                    b.Property<int>("OrderVal")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ParentId")
                        .HasColumnType("TEXT(36)");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT(100)");

                    b.Property<string>("UnitTypeId")
                        .HasColumnType("TEXT(36)");

                    b.HasKey("Id");

                    b.HasIndex("AssignedUnitId");

                    b.HasIndex("ForceTypeId");

                    b.HasIndex("ParentId");

                    b.HasIndex("UnitTypeId");

                    b.ToTable("units", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("S5Server.Models.DocumentTemplate", b =>
                {
                    b.HasOne("S5Server.Models.TemplateDataSet", "DefaultDataSet")
                        .WithMany()
                        .HasForeignKey("DefaultDataSetId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("S5Server.Models.DictTemplateCategory", "TemplateCategory")
                        .WithMany()
                        .HasForeignKey("TemplateCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DefaultDataSet");

                    b.Navigation("TemplateCategory");
                });

            modelBuilder.Entity("S5Server.Models.Soldier", b =>
                {
                    b.HasOne("S5Server.Models.Unit", "AssignedUnit")
                        .WithMany("AssignedSoldiers")
                        .HasForeignKey("AssignedUnitId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("S5Server.Models.Unit", "OperationalUnit")
                        .WithMany("OperationalSoldiers")
                        .HasForeignKey("OperationalUnitId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("S5Server.Models.DictPosition", "Position")
                        .WithMany()
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("S5Server.Models.DictRank", "Rank")
                        .WithMany()
                        .HasForeignKey("RankId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("S5Server.Models.DictSoldierState", "State")
                        .WithMany()
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("S5Server.Models.Unit", "Unit")
                        .WithMany("Soldiers")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedUnit");

                    b.Navigation("OperationalUnit");

                    b.Navigation("Position");

                    b.Navigation("Rank");

                    b.Navigation("State");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("S5Server.Models.TVezhaUser<string>", b =>
                {
                    b.HasOne("S5Server.Models.Soldier", "Soldier")
                        .WithOne("VezhaUser")
                        .HasForeignKey("S5Server.Models.TVezhaUser<string>", "SoldierId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.Navigation("Soldier");
                });

            modelBuilder.Entity("S5Server.Models.TemplateDataSet", b =>
                {
                    b.HasOne("S5Server.Models.DocumentTemplate", "Template")
                        .WithMany("DataSets")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Template");
                });

            modelBuilder.Entity("S5Server.Models.Unit", b =>
                {
                    b.HasOne("S5Server.Models.Unit", "AssignedUnit")
                        .WithMany("AssignedUnits")
                        .HasForeignKey("AssignedUnitId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("S5Server.Models.DictForcesType", "ForceType")
                        .WithMany()
                        .HasForeignKey("ForceTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("S5Server.Models.Unit", "Parent")
                        .WithMany("ChildUnits")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("S5Server.Models.DictUnitType", "UnitType")
                        .WithMany()
                        .HasForeignKey("UnitTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AssignedUnit");

                    b.Navigation("ForceType");

                    b.Navigation("Parent");

                    b.Navigation("UnitType");
                });

            modelBuilder.Entity("S5Server.Models.DocumentTemplate", b =>
                {
                    b.Navigation("DataSets");
                });

            modelBuilder.Entity("S5Server.Models.Soldier", b =>
                {
                    b.Navigation("VezhaUser");
                });

            modelBuilder.Entity("S5Server.Models.Unit", b =>
                {
                    b.Navigation("AssignedSoldiers");

                    b.Navigation("AssignedUnits");

                    b.Navigation("ChildUnits");

                    b.Navigation("OperationalSoldiers");

                    b.Navigation("Soldiers");
                });
#pragma warning restore 612, 618
        }
    }
}
