// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using S5Server.Data;

#nullable disable

namespace S5Server.Migrations
{
    [DbContext(typeof(MainDbContext))]
    [Migration("20260204153340_Add_Drone_Area_ToUnitTask")]
    partial class Add_Drone_Area_ToUnitTask
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("S5Server.Models.DictArea", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT(36)");

                    b.Property<string>("AreaTypeId")
                        .IsRequired()
                        .HasColumnType("TEXT(36)");

                    b.Property<string>("CityCodeId")
                        .HasColumnType("TEXT(36)");

                    b.Property<string>("Comment")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("Coords")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT(100)");

                    b.HasKey("Id");

                    b.HasIndex("AreaTypeId");

                    b.HasIndex("CityCodeId");

                    b.HasIndex("Value")
                        .IsUnique();

                    b.ToTable("dict_area", (string)null);
                });

            modelBuilder.Entity("S5Server.Models.DictAreaType", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT(36)");

                    b.Property<string>("Comment")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("ShortValue")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT(50)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT(100)");

                    b.HasKey("Id");

                    b.HasIndex("Value")
                        .IsUnique();

                    b.ToTable("dict_area_type", (string)null);
                });

            modelBuilder.Entity("S5Server.Models.DictCityCategory", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT(36)");

                    b.Property<string>("CodeId")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("TEXT(1)");

                    b.Property<string>("Comment")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("ShortValue")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT(50)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT(100)");

                    b.HasKey("Id");

                    b.HasIndex("ShortValue")
                        .IsUnique();

                    b.HasIndex("Value")
                        .IsUnique();

                    b.ToTable("dict_city_category", (string)null);
                });

            modelBuilder.Entity("S5Server.Models.DictCityCode", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT(36)");

                    b.Property<string>("CategoryId")
                        .IsRequired()
                        .HasColumnType("TEXT(36)");

                    b.Property<string>("Level1Id")
                        .IsRequired()
                        .HasColumnType("TEXT(20)");

                    b.Property<string>("Level2Id")
                        .HasColumnType("TEXT(20)");

                    b.Property<string>("Level3Id")
                        .HasColumnType("TEXT(20)");

                    b.Property<string>("Level4Id")
                        .HasColumnType("TEXT(20)");

                    b.Property<string>("LevelExtId")
                        .HasColumnType("TEXT(20)");

                    b.Property<string>("ParentId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT(36)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT(100)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Level1Id");

                    b.HasIndex("Level2Id");

                    b.HasIndex("Level3Id");

                    b.HasIndex("Level4Id");

                    b.HasIndex("LevelExtId");

                    b.HasIndex("ParentId");

                    b.ToTable("dict_city_code", (string)null);
                });

            modelBuilder.Entity("S5Server.Models.DictDroneModel", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT(36)");

                    b.Property<string>("Comment")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("DroneTypeId")
                        .IsRequired()
                        .HasColumnType("TEXT(36)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT(100)");

                    b.HasKey("Id");

                    b.HasIndex("DroneTypeId");

                    b.HasIndex("Value")
                        .IsUnique();

                    b.ToTable("dict_drone_model", (string)null);
                });

            modelBuilder.Entity("S5Server.Models.DictDroneType", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT(36)");

                    b.Property<string>("Comment")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("ShortValue")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT(50)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT(100)");

                    b.HasKey("Id");

                    b.HasIndex("Value")
                        .IsUnique();

                    b.ToTable("dict_drone_type", (string)null);
                });

            modelBuilder.Entity("S5Server.Models.DictForcesType", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT(36)");

                    b.Property<string>("Comment")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("ShortValue")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT(50)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT(100)");

                    b.HasKey("Id");

                    b.HasIndex("Value")
                        .IsUnique();

                    b.ToTable("dict_forces_type", (string)null);
                });

            modelBuilder.Entity("S5Server.Models.DictPosition", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT(36)");

                    b.Property<string>("Comment")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT(100)");

                    b.HasKey("Id");

                    b.HasIndex("Value")
                        .IsUnique();

                    b.ToTable("dict_position", (string)null);
                });

            modelBuilder.Entity("S5Server.Models.DictRank", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT(36)");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.Property<string>("Comment")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("NATOCode")
                        .HasColumnType("TEXT");

                    b.Property<int>("OrderVal")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ShortValue")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT(50)");

                    b.Property<string>("SubCategory")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT(100)");

                    b.HasKey("Id");

                    b.HasIndex("Value")
                        .IsUnique();

                    b.ToTable("dict_rank", null, t =>
                        {
                            t.HasComment("Військове звання");
                        });
                });

            modelBuilder.Entity("S5Server.Models.DictSoldierState", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT(36)");

                    b.Property<string>("Comment")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT(100)");

                    b.HasKey("Id");

                    b.HasIndex("Value")
                        .IsUnique();

                    b.ToTable("dict_soldier_state", (string)null);
                });

            modelBuilder.Entity("S5Server.Models.DictTemplateCategory", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT(36)");

                    b.Property<string>("Comment")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("ShortValue")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT(50)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT(100)");

                    b.HasKey("Id");

                    b.HasIndex("Value")
                        .IsUnique();

                    b.ToTable("dict_template_category", (string)null);
                });

            modelBuilder.Entity("S5Server.Models.DictUnitTask", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT(36)");

                    b.Property<decimal>("Amount")
                        .HasColumnType("REAL");

                    b.Property<string>("AreaTypeId")
                        .IsRequired()
                        .HasColumnType("TEXT(36)");

                    b.Property<string>("Comment")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT(100)");

                    b.Property<bool>("WithMeans")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.HasKey("Id");

                    b.HasIndex("AreaTypeId");

                    b.HasIndex("Value")
                        .IsUnique();

                    b.ToTable("dict_unit_task", (string)null);
                });

            modelBuilder.Entity("S5Server.Models.DictUnitTaskItem", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT(36)");

                    b.Property<string>("Comment")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("TemplateCategoryId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT(36)");

                    b.Property<string>("UnitTaskId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT(36)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TemplateCategoryId");

                    b.HasIndex("UnitTaskId", "TemplateCategoryId");

                    b.ToTable("dict_unit_task_item", (string)null);
                });

            modelBuilder.Entity("S5Server.Models.DictUnitType", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT(36)");

                    b.Property<string>("Comment")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("ShortValue")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT(50)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT(100)");

                    b.HasKey("Id");

                    b.HasIndex("Value")
                        .IsUnique();

                    b.ToTable("dict_unit_type", (string)null);
                });

            modelBuilder.Entity("S5Server.Models.DocumentTemplate", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT(36)");

                    b.Property<byte[]>("Content")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT(300)");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT(150)");

                    b.Property<DateTime?>("PublishedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("TemplateCategoryId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT(36)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsPublished");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("TemplateCategoryId");

                    b.ToTable("document_templates", (string)null);
                });

            modelBuilder.Entity("S5Server.Models.DroneModelTask", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT(36)");

                    b.Property<string>("DroneModelId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT(36)");

                    b.Property<int>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1);

                    b.Property<string>("UnitTaskId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT(36)");

                    b.HasKey("Id");

                    b.HasIndex("DroneModelId");

                    b.HasIndex("UnitTaskId");

                    b.HasIndex("UnitTaskId", "DroneModelId")
                        .IsUnique();

                    b.ToTable("drone_model_task", (string)null);
                });

            modelBuilder.Entity("S5Server.Models.Soldier", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT(36)");

                    b.Property<DateOnly?>("ArrivedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("AssignedUnitId")
                        .HasColumnType("TEXT(36)");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ChangedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT(100)");

                    b.Property<string>("Comment")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("DepartedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ExternId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT(50)");

                    b.Property<string>("InvolvedUnitId")
                        .HasColumnType("TEXT(36)");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT(50)");

                    b.Property<string>("MidleName")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT(50)");

                    b.Property<string>("NickName")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT(50)");

                    b.Property<string>("PositionId")
                        .IsRequired()
                        .HasColumnType("TEXT(36)");

                    b.Property<string>("RankId")
                        .IsRequired()
                        .HasColumnType("TEXT(36)");

                    b.Property<string>("StateId")
                        .IsRequired()
                        .HasColumnType("TEXT(36)");

                    b.Property<string>("UnitId")
                        .IsRequired()
                        .HasColumnType("TEXT(36)");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AssignedUnitId");

                    b.HasIndex("InvolvedUnitId");

                    b.HasIndex("PositionId");

                    b.HasIndex("RankId");

                    b.HasIndex("StateId");

                    b.HasIndex("UnitId");

                    b.ToTable("soldiers", null, t =>
                        {
                            t.HasTrigger("trg_soldiers_delete_history");

                            t.HasTrigger("trg_soldiers_insert_history");

                            t.HasTrigger("trg_soldiers_update_history");
                        });
                });

            modelBuilder.Entity("S5Server.Models.SoldierHist", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT(36)");

                    b.Property<DateOnly?>("ArrivedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("AssignedUnitId")
                        .HasColumnType("TEXT(36)");

                    b.Property<string>("AssignedUnitShortName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT(100)");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ChangedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT(100)");

                    b.Property<string>("Comment")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("DepartedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ExternId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT(50)");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT(50)");

                    b.Property<string>("MidleName")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT(50)");

                    b.Property<string>("NickName")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT(50)");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT(10)");

                    b.Property<string>("OperationalUnitId")
                        .HasColumnType("TEXT(36)");

                    b.Property<string>("OperationalUnitShortName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT(100)");

                    b.Property<string>("PositionId")
                        .IsRequired()
                        .HasColumnType("TEXT(36)");

                    b.Property<string>("PositionValue")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT(100)");

                    b.Property<string>("RankId")
                        .IsRequired()
                        .HasColumnType("TEXT(36)");

                    b.Property<string>("RankShortValue")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT(50)");

                    b.Property<string>("SoldierId")
                        .IsRequired()
                        .HasColumnType("TEXT(36)");

                    b.Property<string>("StateId")
                        .IsRequired()
                        .HasColumnType("TEXT(36)");

                    b.Property<string>("StateValue")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT(50)");

                    b.Property<string>("UnitId")
                        .IsRequired()
                        .HasColumnType("TEXT(36)");

                    b.Property<string>("UnitShortName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT(100)");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ValidTo")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Operation");

                    b.HasIndex("SoldierId");

                    b.HasIndex("UnitId");

                    b.HasIndex("SoldierId", "ValidFrom");

                    b.ToTable("soldiers_hist", (string)null);
                });

            modelBuilder.Entity("S5Server.Models.SoldierTask", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT(36)");

                    b.Property<string>("AssignedUnitId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT(36)");

                    b.Property<string>("AssignedUnitShortName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT(100)");

                    b.Property<string>("ChangedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT(100)");

                    b.Property<string>("Comment")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ExternId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT(50)");

                    b.Property<string>("InvolvedUnitId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT(36)");

                    b.Property<string>("InvolvedUnitShortName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT(100)");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT(50)");

                    b.Property<string>("MidleName")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT(50)");

                    b.Property<string>("NickName")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT(50)");

                    b.Property<string>("PositionId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT(36)");

                    b.Property<string>("PositionValue")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT(100)");

                    b.Property<string>("RankId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT(36)");

                    b.Property<string>("RankShortValue")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT(50)");

                    b.Property<string>("SoldierId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT(36)");

                    b.Property<string>("StateId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT(36)");

                    b.Property<string>("StateValue")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT(50)");

                    b.Property<string>("UnitId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT(36)");

                    b.Property<string>("UnitShortName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT(100)");

                    b.Property<string>("UnitTaskId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT(36)");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SoldierId");

                    b.HasIndex("UnitTaskId");

                    b.HasIndex("UnitTaskId", "SoldierId")
                        .IsUnique();

                    b.ToTable("soldiers_task", (string)null);
                });

            modelBuilder.Entity("S5Server.Models.TVezhaUser<string>", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastLoginDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("RegistrationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("SoldierId")
                        .IsRequired()
                        .HasColumnType("TEXT(36)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SoldierId")
                        .IsUnique();

                    b.ToTable("TVezhaUser<string>");
                });

            modelBuilder.Entity("S5Server.Models.TemplateDataSet", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT(36)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DocDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("DocNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT(100)");

                    b.Property<bool>("IsParentDocUsed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsPublished")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT(150)");

                    b.Property<DateTime>("ParentDocDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ParentDocNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT(100)");

                    b.Property<DateTime?>("PublishedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DocNumber");

                    b.HasIndex("IsPublished");

                    b.HasIndex("Name");

                    b.HasIndex("DocDate", "DocNumber")
                        .IsUnique();

                    b.ToTable("template_data_sets", (string)null);
                });

            modelBuilder.Entity("S5Server.Models.Unit", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT(36)");

                    b.Property<string>("AssignedUnitId")
                        .HasColumnType("TEXT(36)");

                    b.Property<string>("ChangedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT(100)");

                    b.Property<string>("Comment")
                        .HasColumnType("TEXT");

                    b.Property<string>("ForceTypeId")
                        .HasColumnType("TEXT(36)");

                    b.Property<bool>("IsInvolved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("MilitaryNumber")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT(100)");

                    b.Property<int>("OrderVal")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ParentId")
                        .HasColumnType("TEXT(36)");

                    b.Property<string>("PersistentLocationId")
                        .HasColumnType("TEXT(36)");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT(100)");

                    b.Property<string>("UnitTypeId")
                        .HasColumnType("TEXT(36)");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AssignedUnitId");

                    b.HasIndex("ForceTypeId");

                    b.HasIndex("ParentId");

                    b.HasIndex("PersistentLocationId");

                    b.HasIndex("UnitTypeId");

                    b.ToTable("units", null, t =>
                        {
                            t.HasTrigger("trg_units_delete_history");

                            t.HasTrigger("trg_units_insert_history");

                            t.HasTrigger("trg_units_update_history");
                        });
                });

            modelBuilder.Entity("S5Server.Models.UnitHist", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT(36)");

                    b.Property<string>("AssignedUnitId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT(36)");

                    b.Property<string>("AssignedUnitShortName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT(100)");

                    b.Property<string>("ChangedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT(100)");

                    b.Property<string>("Comment")
                        .HasColumnType("TEXT");

                    b.Property<string>("ForceTypeId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT(36)");

                    b.Property<string>("ForceTypeShortValue")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT(50)");

                    b.Property<bool>("IsInvolved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("MilitaryNumber")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT(100)");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT(10)");

                    b.Property<int>("OrderVal")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ParentId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT(36)");

                    b.Property<string>("ParentShortName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT(100)");

                    b.Property<string>("PersistentLocationId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT(36)");

                    b.Property<string>("PersistentLocationValue")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT(100)");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT(100)");

                    b.Property<string>("UnitId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT(36)");

                    b.Property<string>("UnitTypeId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT(36)");

                    b.Property<string>("UnitTypeShortValue")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT(50)");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ValidTo")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Operation");

                    b.HasIndex("UnitId");

                    b.HasIndex("UnitId", "ValidFrom");

                    b.ToTable("units_hist", (string)null);
                });

            modelBuilder.Entity("S5Server.Models.UnitTask", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT(36)");

                    b.Property<string>("AreaId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AssignedShortName")
                        .HasColumnType("TEXT(100)");

                    b.Property<string>("AssignedUnitId")
                        .HasColumnType("TEXT(36)");

                    b.Property<string>("ChangedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT(100)");

                    b.Property<string>("DataSetId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT(36)");

                    b.Property<bool>("IsInvolved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsPublished")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("ParentId")
                        .HasColumnType("TEXT(36)");

                    b.Property<string>("ParentShortName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT(100)");

                    b.Property<string>("PersistentLocationId")
                        .HasColumnType("TEXT(36)");

                    b.Property<string>("PersistentLocationValue")
                        .HasColumnType("TEXT(100)");

                    b.Property<DateTime?>("PublishedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("TaskId")
                        .IsRequired()
                        .HasColumnType("TEXT(36)");

                    b.Property<string>("TaskValue")
                        .IsRequired()
                        .HasColumnType("TEXT(100)");

                    b.Property<string>("UnitId")
                        .IsRequired()
                        .HasColumnType("TEXT(36)");

                    b.Property<string>("UnitShortName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT(100)");

                    b.Property<string>("UnitTypeId")
                        .HasColumnType("TEXT(36)");

                    b.Property<string>("UnitTypeName")
                        .HasColumnType("TEXT(100)");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AssignedUnitId");

                    b.HasIndex("DataSetId");

                    b.HasIndex("IsPublished");

                    b.HasIndex("ParentId");

                    b.HasIndex("PersistentLocationId");

                    b.HasIndex("TaskId");

                    b.HasIndex("UnitId");

                    b.HasIndex("UnitTypeId");

                    b.HasIndex("UnitId", "TaskId")
                        .IsUnique();

                    b.ToTable("units_task", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("S5Server.Models.DictArea", b =>
                {
                    b.HasOne("S5Server.Models.DictAreaType", "AreaType")
                        .WithMany("Areas")
                        .HasForeignKey("AreaTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("S5Server.Models.DictCityCode", "CityCode")
                        .WithMany()
                        .HasForeignKey("CityCodeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AreaType");

                    b.Navigation("CityCode");
                });

            modelBuilder.Entity("S5Server.Models.DictCityCode", b =>
                {
                    b.HasOne("S5Server.Models.DictCityCategory", "Category")
                        .WithMany("CityCodes")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("S5Server.Models.DictCityCode", "Level1")
                        .WithMany()
                        .HasForeignKey("Level1Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("S5Server.Models.DictCityCode", "Level2")
                        .WithMany()
                        .HasForeignKey("Level2Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("S5Server.Models.DictCityCode", "Level3")
                        .WithMany()
                        .HasForeignKey("Level3Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("S5Server.Models.DictCityCode", "Level4")
                        .WithMany()
                        .HasForeignKey("Level4Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("S5Server.Models.DictCityCode", "LevelExt")
                        .WithMany()
                        .HasForeignKey("LevelExtId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("S5Server.Models.DictCityCode", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Category");

                    b.Navigation("Level1");

                    b.Navigation("Level2");

                    b.Navigation("Level3");

                    b.Navigation("Level4");

                    b.Navigation("LevelExt");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("S5Server.Models.DictDroneModel", b =>
                {
                    b.HasOne("S5Server.Models.DictDroneType", "DroneType")
                        .WithMany("DroneModels")
                        .HasForeignKey("DroneTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DroneType");
                });

            modelBuilder.Entity("S5Server.Models.DictUnitTask", b =>
                {
                    b.HasOne("S5Server.Models.DictAreaType", "AreaType")
                        .WithMany("UnitTasks")
                        .HasForeignKey("AreaTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AreaType");
                });

            modelBuilder.Entity("S5Server.Models.DictUnitTaskItem", b =>
                {
                    b.HasOne("S5Server.Models.DictTemplateCategory", "TemplateCategory")
                        .WithMany("UnitTaskItems")
                        .HasForeignKey("TemplateCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("S5Server.Models.DictUnitTask", "UnitTask")
                        .WithMany("UnitTaskItems")
                        .HasForeignKey("UnitTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TemplateCategory");

                    b.Navigation("UnitTask");
                });

            modelBuilder.Entity("S5Server.Models.DocumentTemplate", b =>
                {
                    b.HasOne("S5Server.Models.DictTemplateCategory", "TemplateCategory")
                        .WithMany()
                        .HasForeignKey("TemplateCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TemplateCategory");
                });

            modelBuilder.Entity("S5Server.Models.DroneModelTask", b =>
                {
                    b.HasOne("S5Server.Models.DictDroneModel", "DroneModel")
                        .WithMany()
                        .HasForeignKey("DroneModelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("S5Server.Models.UnitTask", "UnitTask")
                        .WithMany("Means")
                        .HasForeignKey("UnitTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DroneModel");

                    b.Navigation("UnitTask");
                });

            modelBuilder.Entity("S5Server.Models.Soldier", b =>
                {
                    b.HasOne("S5Server.Models.Unit", "AssignedUnit")
                        .WithMany("AssignedSoldiers")
                        .HasForeignKey("AssignedUnitId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("S5Server.Models.Unit", "InvolvedUnit")
                        .WithMany("InvolvedSoldiers")
                        .HasForeignKey("InvolvedUnitId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("S5Server.Models.DictPosition", "Position")
                        .WithMany()
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("S5Server.Models.DictRank", "Rank")
                        .WithMany()
                        .HasForeignKey("RankId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("S5Server.Models.DictSoldierState", "State")
                        .WithMany()
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("S5Server.Models.Unit", "Unit")
                        .WithMany("Soldiers")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedUnit");

                    b.Navigation("InvolvedUnit");

                    b.Navigation("Position");

                    b.Navigation("Rank");

                    b.Navigation("State");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("S5Server.Models.SoldierTask", b =>
                {
                    b.HasOne("S5Server.Models.Soldier", "Soldier")
                        .WithMany()
                        .HasForeignKey("SoldierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("S5Server.Models.UnitTask", "UnitTask")
                        .WithMany("SoldiersTask")
                        .HasForeignKey("UnitTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Soldier");

                    b.Navigation("UnitTask");
                });

            modelBuilder.Entity("S5Server.Models.TVezhaUser<string>", b =>
                {
                    b.HasOne("S5Server.Models.Soldier", "Soldier")
                        .WithOne("VezhaUser")
                        .HasForeignKey("S5Server.Models.TVezhaUser<string>", "SoldierId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.Navigation("Soldier");
                });

            modelBuilder.Entity("S5Server.Models.Unit", b =>
                {
                    b.HasOne("S5Server.Models.Unit", "AssignedUnit")
                        .WithMany("AssignedUnits")
                        .HasForeignKey("AssignedUnitId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("S5Server.Models.DictForcesType", "ForceType")
                        .WithMany()
                        .HasForeignKey("ForceTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("S5Server.Models.Unit", "Parent")
                        .WithMany("ChildUnits")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("S5Server.Models.DictArea", "PersistentLocation")
                        .WithMany()
                        .HasForeignKey("PersistentLocationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("S5Server.Models.DictUnitType", "UnitType")
                        .WithMany()
                        .HasForeignKey("UnitTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AssignedUnit");

                    b.Navigation("ForceType");

                    b.Navigation("Parent");

                    b.Navigation("PersistentLocation");

                    b.Navigation("UnitType");
                });

            modelBuilder.Entity("S5Server.Models.UnitTask", b =>
                {
                    b.HasOne("S5Server.Models.Unit", "AssignedUnit")
                        .WithMany()
                        .HasForeignKey("AssignedUnitId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("S5Server.Models.TemplateDataSet", "DataSet")
                        .WithMany("UnitTasks")
                        .HasForeignKey("DataSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("S5Server.Models.Unit", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("S5Server.Models.DictArea", "PersistentLocation")
                        .WithMany()
                        .HasForeignKey("PersistentLocationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("S5Server.Models.DictUnitTask", "Task")
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("S5Server.Models.Unit", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("S5Server.Models.DictUnitType", "UnitType")
                        .WithMany()
                        .HasForeignKey("UnitTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AssignedUnit");

                    b.Navigation("DataSet");

                    b.Navigation("Parent");

                    b.Navigation("PersistentLocation");

                    b.Navigation("Task");

                    b.Navigation("Unit");

                    b.Navigation("UnitType");
                });

            modelBuilder.Entity("S5Server.Models.DictAreaType", b =>
                {
                    b.Navigation("Areas");

                    b.Navigation("UnitTasks");
                });

            modelBuilder.Entity("S5Server.Models.DictCityCategory", b =>
                {
                    b.Navigation("CityCodes");
                });

            modelBuilder.Entity("S5Server.Models.DictCityCode", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("S5Server.Models.DictDroneType", b =>
                {
                    b.Navigation("DroneModels");
                });

            modelBuilder.Entity("S5Server.Models.DictTemplateCategory", b =>
                {
                    b.Navigation("UnitTaskItems");
                });

            modelBuilder.Entity("S5Server.Models.DictUnitTask", b =>
                {
                    b.Navigation("UnitTaskItems");
                });

            modelBuilder.Entity("S5Server.Models.Soldier", b =>
                {
                    b.Navigation("VezhaUser");
                });

            modelBuilder.Entity("S5Server.Models.TemplateDataSet", b =>
                {
                    b.Navigation("UnitTasks");
                });

            modelBuilder.Entity("S5Server.Models.Unit", b =>
                {
                    b.Navigation("AssignedSoldiers");

                    b.Navigation("AssignedUnits");

                    b.Navigation("ChildUnits");

                    b.Navigation("InvolvedSoldiers");

                    b.Navigation("Soldiers");
                });

            modelBuilder.Entity("S5Server.Models.UnitTask", b =>
                {
                    b.Navigation("Means");

                    b.Navigation("SoldiersTask");
                });
#pragma warning restore 612, 618
        }
    }
}
