stages:
- build
- update_manifest

.build_image_template:
  stage: build
  tags:
  - k8s-oci
  image:
    name: moby/buildkit:rootless
  variables:
    SSL_CERT_DIR: "/etc/ssl/certs:${SELFSIGNED_CA_PATH}"
    CACHE_IMAGE: $CI_REGISTRY_IMAGE:cache
    DOCKER_FILE: "Dockerfile"
    IMAGE_TAG: nil
    IMAGE_TAG_LATEST: nil
  before_script:
  - mkdir -p ~/.docker
  - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > ~/.docker/config.json
  script:
  - |
    buildctl \
      --addr "${BUILDKIT_ADDR}" \
      --tlscacert "${BUILDKIT_TLS_CA_FILE}" \
      --tlscert "${BUILDKIT_TLS_CERT_FILE}" \
      --tlskey "${BUILDKIT_TLS_KEY_FILE}" \
      build \
        --frontend dockerfile.v0 \
        --local context=. \
        --local dockerfile=. \
        --frontend-opt filename=./${DOCKER_FILE} \
        --export-cache type=registry,ref=$CACHE_IMAGE \
        --import-cache type=registry,ref=$CACHE_IMAGE \
        --output type=image,name=$CI_REGISTRY_IMAGE:$IMAGE_TAG,push=true \
        --output type=image,name=$CI_REGISTRY_IMAGE:$IMAGE_TAG_LATEST,push=true

build-app-image:
  extends:
  - .build_image_template
  variables:
    IMAGE_TAG: "app-${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHORT_SHA}"
    IMAGE_TAG_LATEST: "app-latest"
    DOCKER_FILE: "Dockerfile"
  rules:
  - if: $CI_COMMIT_BRANCH == "main"
    when: manual
  - if: $CI_COMMIT_BRANCH == "development"
    when: manual

build-db-image:
  extends:
  - .build_image_template
  variables:
    IMAGE_TAG: "db-${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHORT_SHA}"
    IMAGE_TAG_LATEST: "db-latest"
    DOCKER_FILE: "Dockerfile.db"
  rules:
  - if: $CI_COMMIT_BRANCH == "main"
  - if: $CI_COMMIT_BRANCH == "development"
  needs:
  - job: build-app-image

.update_manifest_template:
  stage: update_manifest
  tags:
  - k8s-shared
  needs:
  - job: build-app-image
  - job: build-db-image
  image:
    name: alpine/git:latest
    pull_policy: if-not-present
    entrypoint: [""]
  variables:
    REPO_BRANCH: nil
    ENVIRONMENT: nil
    MANIFEST_BASE_PATH: "${CI_PROJECT_DIR}/apps/s5/overlays/${ENVIRONMENT}/patches"
    DEPLOYMENT_YAML: "${MANIFEST_BASE_PATH}/deployment.yaml"
    PROJECT_URL: s5-group/fluxcd
  before_script:
  - git config user.email "job-runner@gitlab.com822.dom"
  - git config user.name "CI Job Runner"
  - git config http.sslCAInfo "${SELFSIGNED_CA_PATH}/ca.crt"
  - git remote set-url origin https://${GROUP_AT_NAME}:${GROUP_AT_TOKEN}@${CI_SERVER_HOST}/${PROJECT_URL}.git
  - git remote set-url --push origin https://${GROUP_AT_NAME}:${GROUP_AT_TOKEN}@${CI_SERVER_HOST}/${PROJECT_URL}.git
  script:
  - git fetch origin ${REPO_BRANCH}
  - git checkout ${REPO_BRANCH}
  - git pull --rebase origin ${REPO_BRANCH}
  - >
    sed -ir "s|image: $CI_REGISTRY_IMAGE:app-.*|image: $CI_REGISTRY_IMAGE:app-${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHORT_SHA}|" \
        -ir "s|image: $CI_REGISTRY_IMAGE:db-.*|image: $CI_REGISTRY_IMAGE:db-${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHORT_SHA}|" \
        ${DEPLOYMENT_YAML}
  - git add ${DEPLOYMENT_YAML}
  - git commit -m "Update app image tag to ${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHORT_SHA}"
  - git push origin HEAD:${REPO_BRANCH} -o ci.skip

update_manifest-development-job:
  extends: 
  - .update_manifest_template
  rules:
  - if: $CI_COMMIT_BRANCH == "development"
    when: on_success
  variables:
    REPO_BRANCH: "main"
    ENVIRONMENT: "development"
