apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

resources:
  - ../../base

namespace: s5-local

# Подтягиваем замены (replacements) для синхронизации имен БД
replacements:
  - path: ../../base/db-replacements.yaml

# 1. Единый Генератор Секретов из .env
secretGenerator:
  - name: s5-app-secrets
    behavior: merge
    envs:
      - ../../../../.env
  - name: s5-db-credentials # ДОБАВЛЕНО: чтобы база и приложение имели один пароль
    behavior: merge
    envs:
      - ../../../../.env
  - name: s5-https-cert # Добавлена секция для HTTPS (берет KESTREL_CERT_PATH и KESTREL_CERT_PASSWORD из .env)
    envs:
      - ../../../../.env



# 2. Единый Генератор ConfigMap из .env
configMapGenerator:
  - name: s5-app-config
    behavior: merge
    envs:
      - ../../../../.env
  - name: s5-db-params
    behavior: merge
    envs:
      - ../../../../.env

# 3. Подмена образов для локального запуска
images:
  - name: s5-db
    newName: s5-db
    newTag: 18.3-v1.0.0
  - name: s5-server
    newName: s5-server
    newTag: "1.0.3"

# 4. Патчи для переопределения переменных окружения внутри кластера
patches:
  - target:
      kind: ConfigMap
      name: s5-app-config
    patch: |-
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: s5-app-config
      data:
        # Эти значения ПЕРЕКРОЮТ то, что пришло из .env
        DB_HOST: s5-db-cluster-rw
        PrimaryConnection__DB_Host: s5-db-cluster-rw
        ASPNETCORE_ENVIRONMENT: Development
