apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Inherit from the base configuration
resources:
  - ../../base

# Generate the ConfigMap for the development environment
configMapGenerator:
- name: s5-app-config
  literals:
  - ASPNETCORE_ENVIRONMENT=Development
  - DB_HOST=s5-db-cluster-rw # This could be a different dev-specific host

# Generate the Secret from the .env file
secretGenerator:
- name: s5-db-credentials
  envs:
  - dev.env
